### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by DHandsomee** [emre1393/xtreamui_mirror#12]
Hocam selamlar, kurulum yaparken böyle bir hata alıyorum. Bana bu konuda yardımcı olabilir misin?

 ┌──────────────────────────────────────────┐
 │               Encrypting...                                                                           │
 └──────────────────────────────────────────┘

Traceback (most recent call last):
  File "install.py", line 274, in <module>
    encrypt(rHost, rUsername, rPassword, rDatabase, rServerID, rPort)
  File "install.py", line 181, in encrypt
    rf = open('/home/xtreamcodes/iptv_xtream_codes/config', 'wb')
IOError: [Errno 2] No such file or directory: '/home/xtreamcodes/iptv_xtream_codes/config'

**Comment by emre1393** [comment]
make sure your server  can connect to bitbucket server.
