### ISSUE TITLE
Kanal bağlanma sorunu

### ISSUE THREAD

**Issue by xeredin** [emre1393/xtreamui_mirror#4]
Selam
ben kurulumu sorunsuz bir şekilde yaptım güncelleme dahil panel güzel çalışıyor kanal ekliyorum onlarda aktif gözüküyor herşey tamam fakat herhangi bir iptv uygulamasından kanalları izlemek istediğimde bağlantı sağlanamıyor yani kanal listeside geliyor fakat yayını izleyemiyorum iki farklı sunucuda kurulum yapıp denedim aynı sorun var yardımcı olmanız mümkün mü acaba teşekkürler.

**Comment by emre1393** [comment]
geolite2 dosyasını kontrol et.

**Comment by xeredin** [comment]
> geolite2 dosyasını kontrol et.

selam cevabın için teşekkürler. geolite2 dosyasını kontrol ettim bir sürü xtream-ui kurulum kaynaklarınıda inceledim geolite güncelleme olayınıda yaptım fakat sorun hala devam ediyor
