### ISSUE TITLE
ubuntu20 install.py and ubuntu18 issue

### ISSUE THREAD

**Issue by meu0** [emre1393/xtreamui_mirror#9]
I installed ubuntu20 and ubuntu18 but both ends with same issue. Installation went smooth but live stream does play and when downlaod user m3u file it goes to not found.. logs below.

`PHP message: PHP Warning:  Illegal string offset 'mac' in /home/xtreamcodes/iptv_xtream_codes/admin/user.php on line 200
PHP message: PHP Warning:  Illegal string offset 'mac' in /home/xtreamcodes/iptv_xtream_codes/admin/user.php on line 201" while reading response header from upstream, client: XX.XX.XX.XX, server: , request: "GET /user.php?id=1 HTTP/1.1", upstream: "fastcgi://unix:/home/xtreamcodes/iptv_xtream_codes/php/CWcfSP.sock:", host: "XX.XX.XX.XX:25500", referrer: "http://XX.XX.XX.XX:25500/user.php"
2021/03/16 18:04:22 [error] 25315#25315: *114 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/xtreamcodes/iptv_xtream_codes/admin/stream.php on line 810
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/xtreamcodes/iptv_xtream_codes/admin/stream.php on line 822" while reading upstream, client: XX.XX.XX.XX, server: , request: "GET /stream.php?id=1 HTTP/1.1", upstream: "fastcgi://unix:/home/xtreamcodes/iptv_xtream_codes/php/VaiIb8.sock:", host: "XX.XX.XX.XX:25500", referrer: "http://XX.XX.XX.XX:25500/streams.php"
2021/03/16 18:04:29 [error] 25315#25315: *132 open() "/home/xtreamcodes/iptv_xtream_codes/wwwdir/live/1.m3u8" failed (2: No such file or directory), client: XX.XX.XX.XX, server: , request: "GET /live///1.m3u8 HTTP/1.1", host: "XX.XX.XX.XX:25461", referrer: "http://XX.XX.XX.XX:25500/"
2021/03/16 18:04:30 [error] 25315#25315: *133 open() "/home/xtreamcodes/iptv_xtream_codes/wwwdir/live/1.m3u8" failed (2: No such file or directory), client: XX.XX.XX.XX, server: , request: "GET /live///1.m3u8 HTTP/1.1", host: "XX.XX.XX.XX:25461", referrer: "http://XX.XX.XX.XX:25500/"
2021/03/16 18:08:48 [error] 25315#25315: *189 open() "/home/xtreamcodes/iptv_xtream_codes/wwwdir/live/1.m3u8" failed (2: No such file or directory), client: XX.XX.XX.XX, server: , request: "GET /live///1.m3u8 HTTP/1.1", host: "XX.XX.XX.XX:25461", referrer: "http://XX.XX.XX.XX:25500/"
2021/03/16 18:08:49 [error] 25315#25315: *190 open() "/home/xtreamcodes/iptv_xtream_codes/wwwdir/live/1.m3u8" failed (2: No such file or directory), client: XX.XX.XX.XX, server: , request: "GET /live///1.m3u8 HTTP/1.1", host: "XX.XX.XX.XX:25461", referrer: "http://XX.XX.XX.XX:25500/"
2021/03/16 18:13:17 [error] 25315#25315: *428 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/xtreamcodes/iptv_xtream_codes/admin/stream.php on line 810
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/xtreamcodes/iptv_xtream_codes/admin/stream.php on line 822" while reading upstream, client: XX.XX.XX.XX, server: , request: "GET /stream.php?id=1 HTTP/1.1", upstream: "fastcgi://unix:/home/xtreamcodes/iptv_xtream_codes/php/VaiIb8.sock:", host: "XX.XX.XX.XX:25500", referrer: "http://XX.XX.XX.XX:25500/streams.php?filter=1"
2021/03/16 18:30:47 [error] 25321#25321: *716 upstream timed out (110: Connection timed out) while reading response header from upstream, client: XX.XX.XX.XX, server: , request: "GET /api.php?action=stats HTTP/1.1", upstream: "fastcgi://unix:/home/xtreamcodes/iptv_xtream_codes/php/CWcfSP.sock", host: "XX.XX.XX.XX:25500", referrer: "http://XX.XX.XX.XX:25500/dashboard.php"`

**Comment by emre1393** [comment]
yeah, experimantal ubuntu 20 installation script didn't work at all, removed it.
